name: bridge-dummmy-v0
args: []
kwargs: {}
obs_dim: 512
action_dim: 7
action_min: [-1, -1]
action_max: [1, 1]

load_dir: "/absolute/path/to/training_run/directory"

workspace:
  _target_: workspaces.bridge_kitchen.BridgeRepWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_bridge_dataset
  data_directory: ${env_vars.datasets.carla_multipath_town04_merge}
  window_size: ${window_size}
  subset_fraction: 1.0
  encoder:
    _target_: models.resnet.resnet18
    output_dim: 512
    pretrained: True
    freeze_pretrained: True
